# .github/workflows/python-app.yml

name: Python application CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Choose the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Add steps to set up your database here if needed

    - name: Run tests
      run: |
        python -m pip install coverage
        python -m coverage run -m pytest tests
        python -m coverage report -m

